# 确保使用 kramdown 解析器（GitHub Pages 默认支持）
markdown: kramdown

# 配置 MathJax 作为公式引擎
kramdown:
  math_engine: mathjax

## 可选：指定 MathJax 版本（默认会加载最新稳定版）
#mathjax:
#  source: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
